name: Deploy Lost Cats App

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Multi-Arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lucidreline/lost-cats:latest
          platforms: linux/amd64,linux/arm64

  deploy-to-cluster:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Cluster & Redeploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            kubectl rollout restart deployment lost-cats-deployment -n default
